version = 0.1

[default.deploy.parameters]
stack_name = "estudent-prijave"
resolve_s3 = true
s3_prefix = "estudent-prijave"
region = "eu-north-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "ProjectName=\"estudent-prijave\""
image_repositories = []

[default.global.parameters]
region = "eu-north-1"
